### ISSUE TITLE
java.net.ConnectException: Connection refused (Connection refused)

### ISSUE THREAD

**Issue by paul-ovchinnikov** [springdoc/springdoc-openapi-maven-plugin#6]
Output log for `mvn clean verify -Dspring.application.admin.enabled=true` below

Application was started

```
INFO [is,,,] 7851 --- [           main] o.e.jetty.server.AbstractConnector       : Started ServerConnector@3dc82e6a{HTTP/1.1,[http/1.1]}{0.0.0.0:10000}
INFO [is,,,] 7851 --- [           main] o.s.b.web.embedded.jetty.JettyWebServer  : Jetty started on port(s) 10000 (http/1.1) with context path '/'
INFO [is,,,] 7851 --- [           main] com.cdek.is.IsApplication                : Started IsApplication in 10.874 seconds (JVM running for 12.087)
```

springdoc-openapi-maven-plugin:0.3:generate

```
INFO] --- springdoc-openapi-maven-plugin:0.3:generate (integration-test) @ is ---
[ERROR] An error has occured
java.net.ConnectException: Connection refused (Connection refused)
    at java.net.PlainSocketImpl.socketConnect (Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect (AbstractPlainSocketImpl.java:350)
    at java.net.AbstractPlainSocketImpl.connectToAddress (AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect (AbstractPlainSocketImpl.java:188)
    at java.net.SocksSocketImpl.connect (SocksSocketImpl.java:392)
    at java.net.Socket.connect (Socket.java:589)
    at java.net.Socket.connect (Socket.java:538)
    at sun.net.NetworkClient.doConnect (NetworkClient.java:180)
    at sun.net.www.http.HttpClient.openServer (HttpClient.java:463)
    at sun.net.www.http.HttpClient.openServer (HttpClient.java:558)
    at sun.net.www.http.HttpClient.<init> (HttpClient.java:242)
    at sun.net.www.http.HttpClient.New (HttpClient.java:339)
    at sun.net.www.http.HttpClient.New (HttpClient.java:357)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient (HttpURLConnection.java:1220)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0 (HttpURLConnection.java:1156)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect (HttpURLConnection.java:1050)
    at sun.net.www.protocol.http.HttpURLConnection.connect (HttpURLConnection.java:984)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0 (HttpURLConnection.java:1564)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream (HttpURLConnection.java:1492)
    at java.net.HttpURLConnection.getResponseCode (HttpURLConnection.java:480)
    at org.springdoc.maven.plugin.SpringDocMojo.execute (SpringDocMojo.java:43)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
```

pom.xml
```
<plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <wait>1000</wait>
                    <maxAttempts>180</maxAttempts>
                    <jvmArguments>
                        -Dspring.application.admin.enabled=true
                    </jvmArguments>
                </configuration>
                <executions>
                    <execution>
                        <id>pre-integration-test</id>
                        <goals>
                            <goal>start</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>post-integration-test</id>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-maven-plugin</artifactId>
                <version>0.3</version>
                <executions>
                    <execution>
                        <id>integration-test</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Comment by RandyHBH** [comment]
You are missing this in your project, is Kotlin code but I guess you will understand the idea

```
@Configuration
class SecurityConfig() : WebSecurityConfigurerAdapter() {

    @Throws(Exception::class)
    override fun configure(http: HttpSecurity) {
            http
            .csrf().disable()
            .antMatcher("/**")
            .sessionManagement()
            .sessionCreationPolicy(SessionCreationPolicy.NEVER)
            .and()
            .authorizeRequests()
            .antMatchers("/v3/api-docs").permitAll()
            .anyRequest().denyAll()
            .and()
            .httpBasic()
    }
}
```

**Comment by saurabhpro** [comment]
> You are missing this in your project, is Kotlin code but I guess you will understand the idea
> 
> ```
> @Configuration
> class SecurityConfig() : WebSecurityConfigurerAdapter() {
> 
>     @Throws(Exception::class)
>     override fun configure(http: HttpSecurity) {
>             http
>             .csrf().disable()
>             .antMatcher("/**")
>             .sessionManagement()
>             .sessionCreationPolicy(SessionCreationPolicy.NEVER)
>             .and()
>             .authorizeRequests()
>             .antMatchers("/v3/api-docs").permitAll()
>             .anyRequest().denyAll()
>             .and()
>             .httpBasic()
>     }
> }
> ```

could you elaborate a little, I cant translate it to my Java project

**Comment by RandyHBH** [comment]
So, your problem is that you are not allowing access to the route where the swagger is exposed.
You need to create a configuration class and extend from `WebSecurityConfigurerAdapter` and override the method `configure(HttpSecurity http){....}` and allow the access to `"/v3/api-docs"` path

**Comment by saurabhpro** [comment]
> So, your problem is that you are not allowing access to the route where the swagger is exposed.
> You need to create a configuration class and extend from `WebSecurityConfigurerAdapter` and override the method `configure(HttpSecurity http){....}` and allow the access to `"/v3/api-docs"` path

@RandyHBH isn't the above snippet doing the same ?

**Comment by vchernogorov** [comment]
I still experiencing this error using `springdoc-openapi-maven-plugin:1.0` and `spring-boot-maven-plugin:2.4.0-M3` with the same Security config as yours.

**Comment by poteii** [comment]
Hi @RandyHBH 
I've already to add route `"/v3/api-docs"` both of WebSecurityConfigurerAdapter class and yaml file. but it still has Connection Refuse. This is my pom.

>  
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>pre-integration-test</id>
            <goals>
              <goal>start</goal>
            </goals>
          </execution>
          <execution>
            <id>post-integration-test</id>
            <goals>
              <goal>stop</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <skip>true</skip>
          <jvmArguments>-Dspring.application.admin.enabled=true</jvmArguments>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.springdoc</groupId>
        <artifactId>springdoc-openapi-maven-plugin</artifactId>
        <version>1.3</version>
        <executions>
          <execution>
            <id>integration-test</id>
            <goals>
              <goal>generate</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <outputDir>${project.build.directory}/springdoc</outputDir>
        </configuration>
      </plugin>
    </plugins>

**Comment by micobarac** [comment]
I have the exact same problem. Adding permission to the security configuration didn't solve the problem.

Btw, why is this issue closed?

**Comment by RandyHBH** [comment]
Could you share your project or a newly created one that reproduce the issue so I can take a look and see if I can help you?

**Comment by micobarac** [comment]
I have almost the same configuration as @RandyHBH . 

When I run 

`mvn -Pprod,war clean verify -DskipTests=true`

I get:

```
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.2.7.RELEASE:start (pre-integration-test) on project openprovider-cdb: Could not figure out if the application has started: Failed to connect to MBean server at port 9001: Could not invoke shutdown operation: Connection refused to host: 127.0.0.1; nested exception is: 
[ERROR]         java.net.ConnectException: Connection refused (Connection refused)
[ERROR] -> [Help 1]
[ERROR] 
```

**Comment by micobarac** [comment]
The huge question is: **Must the application be app and running on port 8080 prior to running the command above?**

**Comment by micobarac** [comment]
Here is the significant part of pom.xml:

```
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>pre-integration-test</id>
                        <goals>
                            <goal>start</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>post-integration-test</id>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <mainClass>${start-class}</mainClass>
                    <fork>true</fork>
                    <jvmArguments>-Dspring.application.admin.enabled=true</jvmArguments>
                    <!--
                    Enable the line below to have remote debugging of your application on port 5005
                    <jvmArguments>-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005</jvmArguments>
                    -->
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-maven-plugin</artifactId>
                <version>1.3</version>
                <executions>
                    <execution>
                        <phase>integration-test</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <apiDocsUrl>http://localhost:8080/v3/api-docs</apiDocsUrl>
                    <outputFileName>openapi.json</outputFileName>
                    <outputDir>${project.basedir}/target/docs/asciidoc</outputDir>
                </configuration>
            </plugin>
```

I merged the existing spring-boot-maven-plugin settings with the one provided in your docs.

**Comment by micobarac** [comment]
I made it work by removing:

```
                    <execution>
                        <id>pre-integration-test</id>
                        <goals>
                            <goal>start</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>post-integration-test</id>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                    </execution>
```

and running the app on 8080, priror to running maven `mvn -Pprod,war clean verify -DskipTests=true` command.

**Comment by calaracey** [comment]
>The huge question is: Must the application be app and running on port 8080 prior to running the command above?

Is it possible to use this plugin with a spring boot app running on a port other than 8080?

I have tried changing the server url in the configuration but it doesn't seem to fix the connection refused issue.
`<apiDocsUrl>http://localhost:8081/v3/api-docs</apiDocsUrl>`

**Comment by ls-pavel-makhov** [comment]
Had the same problem  - the issue was in the custom path, which was setup in application.yml.

**Comment by pwils025** [comment]
> The huge question is: **Must the application be app and running on port 8080 prior to running the command above?**

This plugin only works if the app server is running before it can make the output file.  In spring boot, we run tests before even building the artifact.  How can I just generate the file without having to run the app server?

**Comment by bnasslahsen** [comment]
No way for that
